// examples/framework/react/src/hooks.ts
import { reactExternalStore, type WritableNode } from "@graphrefly/ts/adapters";
import type { Node } from "@graphrefly/ts/core";
import { useCallback, useMemo, useSyncExternalStore } from "react";

export function useSubscribe<T>(node: Node<T>): T | undefined {
	const store = useMemo(() => reactExternalStore(node), [node]);
	return useSyncExternalStore(store.subscribe, store.getSnapshot, store.getServerSnapshot);
}

export function useStore<T>(node: WritableNode<T>): [T | undefined, (value: T) => void] {
	const value = useSubscribe(node);
	const setValue = useCallback((next: T) => node.set(next), [node]);
	return [value, setValue];
}

// examples/framework/solid/src/hooks.ts
import { nodeSnapshot, subscribeNodeValues, type WritableNode } from "@graphrefly/ts/adapters";
import type { Node } from "@graphrefly/ts/core";
import { type Accessor, createSignal, onCleanup } from "solid-js";

export function useSubscribe<T>(node: Node<T>): Accessor<T | undefined> {
	const [value, setValue] = createSignal<T | undefined>(nodeSnapshot(node));
	const unsubscribe = subscribeNodeValues(node, (next) => setValue(() => next), {
		changesOnly: true,
	});
	onCleanup(unsubscribe);
	return value;
}

export function useStore<T>(node: WritableNode<T>): [Accessor<T | undefined>, (value: T) => void] {
	return [useSubscribe(node), (value) => node.set(value)];
}
